const HtmlWebpackPlugin = require('html-webpack-plugin');
const webpack = require('webpack');
const path = require('path');

module.exports = {
    entry: {
        app: './src/index.js',
    },
    plugins: [
        new HtmlWebpackPlugin({
            filename: "index.html",
            template: "./public/index.html",
            title: "React Toolchain Setup",
            myCustomFooter: 'This app was generated by my custom toolchain'
        }),
        // Use ProvidePlugin, so we don't need to import React inside our components
        new webpack.ProvidePlugin({
            'React': 'react'
        }),
    ],
    module: {
        rules: [
            {
                test: /\.(js|ts)x?$/,
                exclude: /(node_modules|browser_components)/,
                include: /src/,
                loader: 'babel-loader'
            },
            {
                test: /\.(js|ts)x?$/,
                use: 'react-hot-loader/webpack',
                include: /node_modules/
            },
            {
                test: /\.css$/,
                use: ['style-loader', 'css-loader']
            },
            {
                test: /.(png|jpg|gif)$/,
                type: 'asset/resource'
            },
            {
                test: /.svg$/,
                type: 'asset/inline'
            }
        ]
    },
    resolve: { 
        extensions: ['*', '.js', '.jsx', '.ts', '.tsx'],
    },
    output: {
        filename: '[name].[contenthash].js',
        path: path.resolve(__dirname, 'dist'),
        //publicPath: '/', <- only if the output files are in a different folder than index.html
        clean: true,
    },
    optimization: {
        usedExports: true,
        moduleIds: 'deterministic',
        runtimeChunk: 'single',
        splitChunks: {
            cacheGroups: {
                vendor: {
                    test: /[\\/]node_modules[\\/]/,
                    name: 'vendor',
                    chunks: 'all'
                }
            }
        }
    }
};
